#!/usr/bin/env bash
# LexBangla — Database Restore Script
# Supports two modes:
#   walg   → restore from WAL-G base backup + WAL replay (PITR capable)
#   pgdump → restore a specific pg_dump snapshot from OCI Object Storage
#
# Usage:
#   restore.sh walg   [--target-time "2025-01-15 03:00:00 UTC"] [--backup-name base_XXXXXXX]
#   restore.sh pgdump --date 2025-01-15 [--database lexbangla]
#
# IMPORTANT: Stop PostgreSQL before running a WAL-G restore.
#            A pgdump restore can be run against a live cluster into a new DB.

set -euo pipefail

CONFIG_FILE="${LEXBANGLA_BACKUP_CONFIG:-/etc/lexbangla/db-backup.env}"

# ── helpers ───────────────────────────────────────────────────────────────────

log()  { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] [restore] $*"; }
fail() { log "ERROR: $*"; exit 1; }

confirm() {
    local prompt="$1"
    echo ""
    echo "  !! $prompt"
    echo ""
    read -rp "  Type 'yes' to confirm: " answer
    [[ "${answer}" == "yes" ]] || { log "Aborted by user."; exit 1; }
}

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"
}

s3() {
    aws --endpoint-url "${OCI_S3_ENDPOINT}" \
        --region "${OCI_REGION}" \
        s3 "$@"
}

# ── load config ───────────────────────────────────────────────────────────────

[[ -f "${CONFIG_FILE}" ]] || fail "Config file not found: ${CONFIG_FILE}"
# shellcheck source=/dev/null
source "${CONFIG_FILE}"

OCI_S3_ENDPOINT="${OCI_S3_ENDPOINT:-https://${OCI_NAMESPACE}.compat.objectstorage.${OCI_REGION}.oraclecloud.com}"
export AWS_ENDPOINT="${OCI_S3_ENDPOINT}"
export AWS_REGION="${OCI_REGION}"
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_S3_FORCE_PATH_STYLE="${AWS_S3_FORCE_PATH_STYLE:-true}"
export WALG_S3_PREFIX
export WALG_COMPRESSION_METHOD="${WALG_COMPRESSION_METHOD:-brotli}"
export PGHOST PGPORT PGUSER

STAGING_DIR="${STAGING_DIR:-/var/tmp/lexbangla-backup}"
mkdir -p "${STAGING_DIR}"

# ── argument parsing ──────────────────────────────────────────────────────────

RESTORE_MODE="${1:-}"
shift || true

TARGET_TIME=""
BACKUP_NAME="LATEST"
RESTORE_DATE=""
RESTORE_DATABASE="${PGDUMP_DATABASES%% *}"  # default: first configured DB
RESTORE_TARGET_DB=""                         # optional: restore into this DB name

while [[ $# -gt 0 ]]; do
    case "$1" in
        --target-time)   TARGET_TIME="$2";       shift 2 ;;
        --backup-name)   BACKUP_NAME="$2";       shift 2 ;;
        --date)          RESTORE_DATE="$2";      shift 2 ;;
        --database)      RESTORE_DATABASE="$2";  shift 2 ;;
        --target-db)     RESTORE_TARGET_DB="$2"; shift 2 ;;
        *) fail "Unknown argument: $1" ;;
    esac
done

# ── WAL-G restore ─────────────────────────────────────────────────────────────

restore_walg() {
    require_cmd wal-g

    log "=== WAL-G restore mode ==="
    log "  Backup name : ${BACKUP_NAME}"
    log "  Target time : ${TARGET_TIME:-<latest consistent state>}"
    log "  PGDATA      : ${PGDATA:?PGDATA must be set}"

    # Safety check: PGDATA must exist but PostgreSQL must not be running
    if pg_ctl status -D "${PGDATA}" >/dev/null 2>&1; then
        fail "PostgreSQL is still running. Stop it before restoring: pg_ctl stop -D ${PGDATA}"
    fi

    confirm "This will OVERWRITE ${PGDATA}. All current data will be lost."

    log "Listing available WAL-G base backups..."
    wal-g backup-list --detail || true

    # Move aside the current data directory rather than deleting it immediately
    local backup_dir="${PGDATA}_pre_restore_$(date -u '+%Y%m%dT%H%M%SZ')"
    log "Moving existing PGDATA to ${backup_dir} (safety copy)..."
    mv "${PGDATA}" "${backup_dir}"
    mkdir -p "${PGDATA}"
    chmod 700 "${PGDATA}"

    log "Running wal-g backup-fetch..."
    if [[ "${BACKUP_NAME}" == "LATEST" ]]; then
        wal-g backup-fetch "${PGDATA}" LATEST
    else
        wal-g backup-fetch "${PGDATA}" "${BACKUP_NAME}"
    fi

    # Write recovery configuration (PostgreSQL 12+ uses postgresql.auto.conf / recovery.signal)
    local pg_major
    pg_major="$(pg_config --version | grep -oP '\d+' | head -1)"

    if [[ "${pg_major}" -ge 12 ]]; then
        log "Writing recovery config (PG ${pg_major})..."
        touch "${PGDATA}/recovery.signal"

        {
            echo "# WAL-G restore — generated by restore.sh"
            echo "restore_command = 'wal-g wal-fetch %f %p'"
            if [[ -n "${TARGET_TIME}" ]]; then
                echo "recovery_target_time = '${TARGET_TIME}'"
                echo "recovery_target_action = 'promote'"
            fi
        } >> "${PGDATA}/postgresql.auto.conf"
    else
        log "Writing recovery.conf (PG ${pg_major})..."
        {
            echo "restore_command = 'wal-g wal-fetch %f %p'"
            if [[ -n "${TARGET_TIME}" ]]; then
                echo "recovery_target_time = '${TARGET_TIME}'"
                echo "recovery_target_action = 'promote'"
            fi
        } > "${PGDATA}/recovery.conf"
    fi

    log ""
    log "Restore data fetched. Next steps:"
    log "  1. Review ${PGDATA}/postgresql.auto.conf (or recovery.conf)"
    log "  2. Start PostgreSQL: pg_ctl start -D ${PGDATA} -l /var/log/postgresql/restore.log"
    log "  3. Monitor: tail -f /var/log/postgresql/restore.log"
    log "  4. PostgreSQL will replay WAL and promote automatically."
    log ""
    log "Old data directory preserved at: ${backup_dir}"
}

# ── pg_dump restore ───────────────────────────────────────────────────────────

restore_pgdump() {
    require_cmd aws
    require_cmd psql
    require_cmd createdb

    [[ -n "${RESTORE_DATE}" ]] || fail "--date is required for pgdump mode (e.g. --date 2025-01-15)"

    local target_db="${RESTORE_TARGET_DB:-${RESTORE_DATABASE}_restored_${RESTORE_DATE//-/}}"
    local object_key="pgdump/${RESTORE_DATE}/${RESTORE_DATABASE}.sql.gz"
    local local_dump="${STAGING_DIR}/${RESTORE_DATABASE}_${RESTORE_DATE}.sql.gz"

    log "=== pg_dump restore mode ==="
    log "  Source snapshot : ${RESTORE_DATE}"
    log "  Source database : ${RESTORE_DATABASE}"
    log "  Target database : ${target_db}"
    log "  Object key      : s3://${OCI_BUCKET}/${object_key}"

    # Verify the snapshot exists
    log "Checking snapshot availability..."
    s3 ls "s3://${OCI_BUCKET}/${object_key}" \
        || fail "Snapshot not found: s3://${OCI_BUCKET}/${object_key}"

    confirm "This will create database '${target_db}'. Existing connections are unaffected."

    log "Downloading dump from OCI Object Storage..."
    s3 cp "s3://${OCI_BUCKET}/${object_key}" "${local_dump}" --no-progress

    log "Creating target database '${target_db}'..."
    createdb \
        --host="${PGHOST}" \
        --port="${PGPORT}" \
        --username="${PGUSER}" \
        "${target_db}" \
        || fail "createdb failed. Does the user have CREATEDB privilege?"

    log "Restoring dump into '${target_db}'..."
    zcat "${local_dump}" | psql \
        --host="${PGHOST}" \
        --port="${PGPORT}" \
        --username="${PGUSER}" \
        --dbname="${target_db}" \
        --set ON_ERROR_STOP=1 \
        2>&1 | while IFS= read -r line; do log "$line"; done

    rm -f "${local_dump}"

    log ""
    log "Restore complete. Verify:"
    log "  psql -h ${PGHOST} -U ${PGUSER} -d ${target_db} -c '\\dt'"
    log ""
    log "To rename it to the production name (requires no active connections):"
    log "  psql -U ${PGUSER} -c \"ALTER DATABASE ${RESTORE_DATABASE} RENAME TO ${RESTORE_DATABASE}_old;\""
    log "  psql -U ${PGUSER} -c \"ALTER DATABASE ${target_db} RENAME TO ${RESTORE_DATABASE};\""
}

# ── list available backups ────────────────────────────────────────────────────

list_backups() {
    require_cmd wal-g
    log "=== Available WAL-G base backups ==="
    export AWS_ENDPOINT="${OCI_S3_ENDPOINT}"
    wal-g backup-list --detail

    log ""
    log "=== Available pg_dump snapshots (last 10) ==="
    s3 ls "s3://${OCI_BUCKET}/pgdump/" \
        | sort -rk1,2 \
        | head -10 \
        | awk '{print $2}'
}

# ── dispatch ──────────────────────────────────────────────────────────────────

case "${RESTORE_MODE}" in
    walg)   restore_walg ;;
    pgdump) restore_pgdump ;;
    list)   list_backups ;;
    *)
        echo "Usage: $0 {walg|pgdump|list} [options]"
        echo ""
        echo "  walg   [--backup-name NAME] [--target-time 'YYYY-MM-DD HH:MM:SS UTC']"
        echo "  pgdump --date YYYY-MM-DD [--database DB] [--target-db NEWDB]"
        echo "  list"
        exit 1
        ;;
esac
